[application]
name = "hybrid-overlay"
public_dir = "../web-public"

[web.resource.dev]
script = ["/dioxus-hotpatch-wasm-bindgen-shim.js"]

[bundle]
identifier = "dev.sparsha.hybrid_overlay"
version = "0.1.0"
