[application]
name = "kitchen-sink"
public_dir = "../web-public"

[web.resource.dev]
script = ["/dioxus-hotpatch-wasm-bindgen-shim.js"]

[bundle]
identifier = "dev.sparsha.kitchen_sink"
version = "0.1.0"
